steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_IMG:latest', '-f', '$_SRVC/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_IMG:latest']
options:
  machineType: 'E2_HIGHCPU_8'